apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn-client
spec:
  selector:
    matchLabels:
      app: openvpn-client
      vpn: vpn-id
  replicas: 1
  template:
    metadata:
      labels:
        app: openvpn-client
        vpn: vpn-id
    spec:
      volumes:
        - name: vpn-config
          secret:
            secretName: vpn-config
            items:
                - key: client.ovpn
                  path: client.ovpn
        - name: vpn-auth
          secret:
            secretName: vpn-auth
            items:
                - key: auth.txt
                  path: auth.txt
        - name: route-script
          configMap:
            name: route-script
            items:
              - key: route-override.sh
                path: route-override.sh
        - name: tmp
          emptyDir: {}
      initContainers:
      - name: vpn-route-init
        image: busybox
        command: ['/bin/sh', '-c', 'cp /vpn/route-override.sh /tmp/route/route-override.sh; chown root:root /tmp/route/route-override.sh; chmod o+x /tmp/route/route-override.sh;']
        volumeMounts:
          - name: tmp
            mountPath: /tmp/route
          - name: route-script
            mountPath: /vpn/route-override.sh
            subPath: route-override.sh
      containers:
        - name: vpn
          image: dperson/openvpn-client
          command: ["/bin/sh","-c"]
          args: ["openvpn --config 'vpn/client.ovpn' --auth-user-pass 'vpn/auth.txt' --script-security 3 --route-up /tmp/route/route-override.sh;"]
          stdin: true
          tty: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          # env:
          #   - name: TZ
          #     value: "Turkey"
          volumeMounts:
            - name: vpn-config
              mountPath: /vpn/client.ovpn
              subPath: client.ovpn
            - name: vpn-auth
              mountPath: /vpn/auth.txt
              subPath: auth.txt
            - name: tmp
              mountPath: /tmp/route
        - name: app1
          image: python:3.6-stretch
          command:
            - sleep
            - "100000"
          tty: true
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4