apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server-deployment
  namespace: drone
  labels:
    app: drone-server-deployment
  annotations:
spec:
  selector:
    matchLabels:
      app: drone-server-deployment
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drone-server-deployment
    spec:
      containers:
      - name: drone-server-deployment
        image: drone/drone:1.6.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DRONE_USER_CREATE 
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_USER_CREATE
        - name: DRONE_DATABASE_DRIVER
          value: postgres
        - name: DRONE_DATABASE_DATASOURCE 
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_DATABASE_DATASOURCE
        - name: DRONE_SERVER_PROTO
          value: http
        - name: DRONE_GITEA_SERVER
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_SERVER_HOST
        - name: DRONE_SERVER_HOST 
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_SERVER_HOST
        - name: DRONE_GITEA_CLIENT_ID 
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_GITEA_CLIENT_ID
        - name: DRONE_GITEA_CLIENT_SECRET 
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_GITEA_CLIENT_SECRET
        - name: DRONE_RPC_SECRET 
          valueFrom:
            secretKeyRef:
              name: drone-server-secret
              key: DRONE_RPC_SECRET
