apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: f6e65efd-d14f-49ae-9d05-6072f7982be3   #Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: aysILNKU3I_FEDvGcjIDtBvc6GX_TyW9a2wvtVgYX9U=  #Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 394a8201ea2fb490547404df5f7135fa           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: 192.168.99.132:30500
  DRONE_GITEA_SERVER: http://192.168.99.132:30280/
