apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 479339d7-45bf-48aa-93bd-27f6a1ecb5f7    #Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: 41b5nHLukuEk1SRdwO9jLF7yIuKgOdzZ16CftJEnuH8=  #Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 394a8201ea2fb490547404df5f7135fa           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_SERVER_HOST: droneserver.sotera.com
  DRONE_GITEA_SERVER: http://gitea-charts-0.gitea.svc.cluster.local:3000/
