apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 2e6c5c91-6925-4e78-9a01-dc0b95b20739    #Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: xuViHowHhcYGHT-_WHxYk_2UX45KZkqVfXgw3win2ns=  #Get this from Gitea OAUTH
  DRONE_RPC_SECRET: a7235d057a01fc9d0d820d6b765c8c03           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true,token:a7235d057a01fc9d0d820d6b765c8c03
  DRONE_SERVER_HOST: drone.sotera.com # GITEA IS gonaa call back this URL
  DRONE_GITEA_SERVER: http://gitea-charts-0.gitea.svc.cluster.local:3000/
