apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 33d52389-545b-4920-adac-03518a68e0e4   # Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: rve-8WP_sBzdkIuq0v3Wop1krb6RICwZT685tI9nh2g=  # Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 54bd4c6f5cac9ebb7e12242f7ba20dad           # openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: drone.soteria.com # public ip address where we wanna run drone
  DRONE_GITEA_SERVER: http://192.168.64.18:30280/
  