apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 08808ff2-088f-40f1-8ac0-94ef6311a624   #Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: E4pNKj_6siSchLcXrT53ZA7-pw_ydaOjGKJxzhpHuDQ=  #Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 394a8201ea2fb490547404df5f7135fa           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: 84bb3c4b53dd.ngrok.io 
  DRONE_GITEA_SERVER: http://46e32f1fd6f2.ngrok.io
