apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 4c9388a6-a43e-4dd2-bfb7-ac6759838fee    #Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: Sizx_yaQK7SIvHQpBvZLnNqUs9_jcYihZw9o2-229rs=  #Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 394a8201ea2fb490547404df5f7135fa           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_SERVER_HOST: drone.sotera.com
  DRONE_GITEA_SERVER: http://gitea-charts-0.gitea.svc.cluster.local:3000/
