apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 272e556a-4a80-4a8f-a791-196405ba4b83   #Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: LkvwXFUUh4Yjs8uIzzbBM_dZ5Ae-im2QfRBUlO7Ax1c=  #Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 37b927dec7832b0d4d773687665e4038           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: drone.soteria.com # public ip address where we wanna run drone
  DRONE_GITEA_SERVER: http://gitea-charts-http.gitea.svc.cluster.local:3000/
