apiVersion: v1
kind: Service
metadata:
  name: droneserver
  labels:
    app: drone-server-deployment
spec:
  type: ClusterIP
  selector:
    app: drone-server-deployment
  #ports:
  # - protocol: TCP
  #   name: drone
  #   port: 8000
  #   targetPort: 8000
  #   nodePort: 30567
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
