apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-test
  name: web-test
spec:
  type: NodePort
  ports:
  - nodePort: 31318
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: web-test