# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: gitea-reporter-configmap
# data:
#   GITEA_USERNAME: gitea_admin
#   GITEA_HOST: 192.168.64.19
#   GITEA_PORT: "30280"
#   GITEA_REPO: testing_repo
#   SONAR_URL: http://192.168.64.19:30281
#   SONAR_LOGIN: admin
# ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-reporter-configmap
  namespace: drone
data:
  drone.conf: |
    GITEA_TOKEN={{GITEA_TOKEN}}
    GITEA_USERNAME={{GITEA_USERNAME}}
    GITEA_HOST={{GITEA_HOST}}
    GITEA_PORT={{GITEA_PORT}}
    GITEA_REPO={{GITEA_REPO}}
    SONAR_URL={{SONAR_URL}}
    SONAR_LOGIN={{SONAR_USER}}
    SONAR_PASSWORD={{SONAR_PASSWORD}}
    SONAR_KEY={{GITEA_USERNAME}}:{{GITEA_REPO}}

# S3_BUCKET_NAME=YOUR-S3-BUCKET-NAME
# SNYK_TOKEN=YOUR-SNYK-TOKEN