apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: 8ddedd7a-99e2-4f61-9322-589a9288a457   # Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: DslKi0kJreoloU1Qa3r0gpVGP_o6jwiUpSqvCTbqxlc= # Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 1f9b08554306943600d5357370167efd        # openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: 192.168.64.19:32175 # public ip address where we wanna run drone. `minikube service --url droneserver -n drone`
  DRONE_GITEA_SERVER: http://192.168.64.19:30280 # `minikube service --url gitea-charts-http -n gitea`

  # http://gitea-charts-http.gitea.svc.cluster.local:3000/
