apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: c5700fd8-8708-4e26-bc1d-d46feb35a1c3   # Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: fYKbCeAsp5NpMSHTcnoS_vqIVoofXIhm1BbtOejlahE=  # Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 9135fb9a4ca24b262ac947cafff0388e           # openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: drone.soteria.com # public ip address where we wanna run drone
  DRONE_GITEA_SERVER: http://gitea-charts-http.gitea.svc.cluster.local:3000/