apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
stringData:
  DRONE_GITEA_CLIENT_ID: d5da25f6-66ed-4af1-92ed-f3a245805b97   # Get this from Gitea OAUTH
  DRONE_GITEA_CLIENT_SECRET: JBNbJ5CgmN_OsFSbrScg4mDzYZHUu_379utfFam0es0= # Get this from Gitea OAUTH
  DRONE_RPC_SECRET: 5e3009e324beca7571f78fab311d423d         # openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: username:gitea_admin,admin:true
  DRONE_USER_FILTER: gitea_admin
  DRONE_SERVER_HOST: 192.168.64.18:32175 # public ip address where we wanna run drone. `minikube service --url droneserver -n drone`
  DRONE_GITEA_SERVER: http://192.168.64.18:30280 # `minikube service --url gitea-charts-http -n gitea`

  # http://gitea-charts-http.gitea.svc.cluster.local:3000/
