apiVersion: v1
kind: Service
metadata:
  name: droneserver
  labels:
    app: drone-server-deployment
spec:
  type: NodePort
  selector:
    app: drone-server-deployment
  ports:
    - protocol: TCP
      name: http
      nodePort: 32175
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      nodePort: 32176
      port: 443
      targetPort: 443
